### ISSUE TITLE
Critical failures should raise an e-mail notification, if possible

### ISSUE THREAD

**Issue by Xophmeister** [wtsi-hgi/hgi-vault#15]
When an error occurs that causes the software to crash (e.g., uncaught exceptions), then an e-mail notification should be sent so we don't have to actively monitor the logs. This would be particularly useful for Sandman runs. (At the moment, this functionality is tacked on to the cron job script's wrapper.)

Some amount of configuration is going to need to be read for this to work, which becomes a chicken vs. egg problem if that's the source of the error.

**Comment by sb10** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As an admin, I want to be emailed about critical failures in sandman, so that I don't have to check the logs](https://trello.com/c/Wvb9Oouu/21-as-an-admin-i-want-to-be-emailed-about-critical-failures-in-sandman-so-that-i-dont-have-to-check-the-logs)

**Comment by vviyer** [comment]
emailing the location of the log file is good enough for now
