### ISSUE TITLE
Files owned by root can't be found in LDAP and stop Sandman

### ISSUE THREAD

**Issue by michael-grace** [wtsi-hgi/hgi-vault#18]
Files owned by root have an ID of `0` which sandman won't find in the LDAP records, so it'll stop. Although stopping immediately if something goes wrong is what we want, this case should be dealt with individually (i.e. skipping the files)

**Comment by Xophmeister** [comment]
I have switched the cron job off to allow a fix to be implemented. The following needs to be done to clear up the database:

```sql
delete from files where owner = 0;
```

The schema is set up to do a cascade delete, so all referenced records in other tables will be removed correctly.

I recommend the following for a fix:

1. Don't issue a warning or attempt a delete if the file cannot be actioned (i.e., deleted) by the running user; instead skip the file but log (at the `ERROR` level, rather than `WARNING`) that it's passed thresholds, during the Sandman sweep. Whether a file can be actioned by Vault/Sandman can be established with [`VaultFile.can_add`](https://github.com/wtsi-hgi/hgi-vault/blob/e7b7fa445c4ed7f63503fc07a84e9da8326725b5/api/vault/file.py#L168-L200). This will cover not only the case of files owned by `root`, but any other errant file that has incorrect permissions.

2. Update the [IdM](https://github.com/wtsi-hgi/hgi-vault/blob/e7b7fa445c4ed7f63503fc07a84e9da8326725b5/api/idm/idm.py) implementation to be explicitly aware of `uid` 0; i.e., treating `root` as a special case to avoid the LDAP lookup coming up short.

**Comment by Xophmeister** [comment]
...it _may_ even be worth putting a constraint on the database schema to prohibit `uid` 0.

**Comment by Xophmeister** [comment]
Compromise: The failing behaviour is actually how Vault/Sandman was originally designed, such that unexpected state can stop the process quickly to reduce any potential damage. As such, what I suggest is a slight tweak to the above: Rather than just skipping a file and logging an `ERROR`, if `can_add` is `False` then it should issue a `CRITICAL` and exit immediately.

i.e., Fail gracefully and emit a useful error message, rather than the above behaviour of skipping or the current behaviour of failing downstream with a Python stack trace.

**Comment by sb10** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As an admin, I want sandman to fail early on root-owned files, so that it doesn't waste time and try to email root](https://trello.com/c/bld6pLoH/17-as-an-admin-i-want-sandman-to-fail-early-on-root-owned-files-so-that-it-doesnt-waste-time-and-try-to-email-root)
