### ISSUE TITLE
Minimal number of owners required for a vault

### ISSUE THREAD

**Issue by Xophmeister** [wtsi-hgi/hgi-vault#3]
It might be useful to specify, as part of the data retention policy, the minimal number of owners (i.e., those who will get actionable e-mails) that a group must have before a vault can be created.

**Comment by sb10** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As an admin, I want a minimum number of owners of a project before sandman is applied to it, so that more than one person receives and can respond to notification emails](https://trello.com/c/tuQ0XfM4/26-as-an-admin-i-want-a-minimum-number-of-owners-of-a-project-before-sandman-is-applied-to-it-so-that-more-than-one-person-receives)
